### ISSUE TITLE
Create FAQ entry: Sorting delivery highlighting rule 'Observed' does not affect legend

### ISSUE THREAD

**Issue by afalenski** [SiLeBAT/fcl-web-app#597]
**To Reproduce**
If the highlighting rule 'Observed' is put to the topmost position in both station and delivery highlighting lists and if a delivery is observed, the rule 'Observed' is NOT at the first position in the legend. It is only at the first position if a station is observed.

**Expected behavior**
It was agreed upon that default highlighting rules are sorted in the station highlighting rules list and that this should affect also the delivery highlighting rules. If a delivery is observed and both the station and the delivery highlighting rules "Observed" are at the top positions in both highlighting lists, 'Observed is expected to be at the top position in the legend, too; especially because it is like this in the legend if a station is observed.

**Comment by bfrgottscma** [comment]
Due to the fact that station highlighting has a higher priority than delivery highlighting. In my eyes not a problem. We will not be able to prevent all sorting conflicts in the legend between stations and deliveries anyway.

**Comment by bfrgottscma** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/fcl-5821aea8cbe1b0da7b31ee86/issues/SiLeBAT/fcl-client/597?planning-poker) with ZenHub @afalenski @GerberI @MicheleK17 @ruegenbfr
